version: "3.9"
services:
  # Server
  app:
    build: .
    env_file:
      - ../env/backend.env
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
