version: '3.7'
services:
  database:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=subscribe
      - MONGO_INIT_ROOT_USERNAME=root
      - MONGO_INIT_ROOT_PASSWORD=rootpassword
    volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
    - 27017:27017
    expose:
      - 27017
volumes:
  data: